import esbuild from "esbuild";
import process from "process";
import { sassPlugin } from "esbuild-sass-plugin";
import postcss from "postcss";
import autoprefixer from "autoprefixer";
import builtins from "builtin-modules";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === "production";

const build = async () => {
	const context = await esbuild.context({
		banner: {
			js: banner,
		},
		entryPoints: {
			main: "src/main.ts",
			styles: "src/styles/styles.scss",
		},
		outdir: "demo/.obsidian/plugins/brumes",
		bundle: true,
		external: [
			"obsidian",
			"electron",
			"@codemirror/autocomplete",
			"@codemirror/collab",
			"@codemirror/commands",
			"@codemirror/language",
			"@codemirror/lint",
			"@codemirror/search",
			"@codemirror/state",
			"@codemirror/view",
			"@lezer/common",
			"@lezer/highlight",
			"@lezer/lr",
			...builtins,
		],
		format: "cjs",
		target: "es2018",
		logLevel: "info",
		sourcemap: prod ? false : "inline",
		treeShaking: true,
		plugins: [
			sassPlugin({
				async transform(source) {
					const { css } = await postcss([autoprefixer]).process(
						source,
						{ from: undefined }
					);
					return css;
				},
			}),
		],
	});

	if (prod) {
		await context.rebuild();
		process.exit(0);
	} else {
		await context.watch();
	}
};

build();
